// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.request;

import ch.dreamweb.client.request.SettingRequest;
import ch.dreamweb.shared.gae.MakesGaeRequests;
import ch.dreamweb.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory, MakesGaeRequests {

    SettingRequest settingRequest();
}
