// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.request;

import ch.dreamweb.client.proxy.SettingProxy;
import ch.dreamweb.client.proxy.StatisticProxy;
import ch.dreamweb.client.proxy.TestStatisticProxy;
import com.google.web.bindery.requestfactory.shared.EntityProxy;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public abstract class ApplicationEntityTypesProcessor<T> {

    private final T defaultValue;

    private T result;

    public ApplicationEntityTypesProcessor() {
        defaultValue = null;
    }

    public ApplicationEntityTypesProcessor(T defaultValue) {
        this.defaultValue = defaultValue;
    }

    public static Set<java.lang.Class<? extends com.google.web.bindery.requestfactory.shared.EntityProxy>> getAll() {
        Set<Class<? extends EntityProxy>> rtn = new HashSet<Class<? extends EntityProxy>>();
        rtn.add(SettingProxy.class);
        rtn.add(StatisticProxy.class);
        rtn.add(TestStatisticProxy.class);
        return Collections.unmodifiableSet(rtn);
    }

    private static void process(ch.dreamweb.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Class<?> clazz) {
        if (SettingProxy.class.equals(clazz)) {
            processor.handleSetting((SettingProxy) null);
            return;
        }
        if (StatisticProxy.class.equals(clazz)) {
            processor.handleStatistic((StatisticProxy) null);
            return;
        }
        if (TestStatisticProxy.class.equals(clazz)) {
            processor.handleTestStatistic((TestStatisticProxy) null);
            return;
        }
        processor.handleNonProxy(null);
    }

    private static void process(ch.dreamweb.client.managed.request.ApplicationEntityTypesProcessor<?> processor, Object proxy) {
        if (proxy instanceof SettingProxy) {
            processor.handleSetting((SettingProxy) proxy);
            return;
        }
        if (proxy instanceof StatisticProxy) {
            processor.handleStatistic((StatisticProxy) proxy);
            return;
        }
        if (proxy instanceof TestStatisticProxy) {
            processor.handleTestStatistic((TestStatisticProxy) proxy);
            return;
        }
        processor.handleNonProxy(proxy);
    }

    public void handleNonProxy(Object object) {
    }

    public abstract void handleSetting(SettingProxy proxy);

    public abstract void handleStatistic(StatisticProxy proxy);

    public abstract void handleTestStatistic(TestStatisticProxy proxy);

    public T process(Class<?> clazz) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, clazz);
        return result;
    }

    public T process(Object proxy) {
        setResult(defaultValue);
        ApplicationEntityTypesProcessor.process(this, proxy);
        return result;
    }

    protected void setResult(T result) {
        this.result = result;
    }
}
