// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.dreamweb.domain;

import ch.dreamweb.domain.Setting;
import ch.dreamweb.domain.SettingDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SettingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SettingDataOnDemand: @Component;
    
    private Random SettingDataOnDemand.rnd = new SecureRandom();
    
    private List<Setting> SettingDataOnDemand.data;
    
    public Setting SettingDataOnDemand.getNewTransientSetting(int index) {
        Setting obj = new Setting();
        setLogin(obj, index);
        return obj;
    }
    
    public void SettingDataOnDemand.setLogin(Setting obj, int index) {
        String login = "login_" + index;
        obj.setLogin(login);
    }
    
    public Setting SettingDataOnDemand.getSpecificSetting(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Setting obj = data.get(index);
        Long id = obj.getId();
        return Setting.findSetting(id);
    }
    
    public Setting SettingDataOnDemand.getRandomSetting() {
        init();
        Setting obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Setting.findSetting(id);
    }
    
    public boolean SettingDataOnDemand.modifySetting(Setting obj) {
        return false;
    }
    
    public void SettingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Setting.findSettingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Setting' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Setting>();
        for (int i = 0; i < 10; i++) {
            Setting obj = getNewTransientSetting(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
