// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.dreamweb.domain;

import ch.dreamweb.domain.StatisticIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StatisticIntegrationTest_Roo_Configurable {
    
    declare @type: StatisticIntegrationTest: @Configurable;
    
}
