// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.activity;

import ch.dreamweb.client.managed.request.ApplicationEntityTypesProcessor;
import ch.dreamweb.client.managed.request.ApplicationRequestFactory;
import ch.dreamweb.client.managed.ui.SettingListView;
import ch.dreamweb.client.managed.ui.SettingMobileListView;
import ch.dreamweb.client.managed.ui.StatisticListView;
import ch.dreamweb.client.managed.ui.StatisticMobileListView;
import ch.dreamweb.client.proxy.SettingProxy;
import ch.dreamweb.client.proxy.StatisticProxy;
import ch.dreamweb.client.scaffold.ScaffoldApp;
import ch.dreamweb.client.scaffold.place.ProxyListPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleSetting(SettingProxy isNull) {
                setResult(new SettingListActivity(requests, ScaffoldApp.isMobile() ? SettingMobileListView.instance() : SettingListView.instance(), placeController));
            }

            @Override
            public void handleStatistic(StatisticProxy isNull) {
                setResult(new StatisticListActivity(requests, ScaffoldApp.isMobile() ? StatisticMobileListView.instance() : StatisticListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
