// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.activity;

import ch.dreamweb.client.managed.request.ApplicationRequestFactory;
import ch.dreamweb.client.managed.ui.StatisticDetailsView;
import ch.dreamweb.client.managed.ui.StatisticEditView;
import ch.dreamweb.client.managed.ui.StatisticListView;
import ch.dreamweb.client.managed.ui.StatisticMobileDetailsView;
import ch.dreamweb.client.managed.ui.StatisticMobileEditView;
import ch.dreamweb.client.proxy.StatisticProxy;
import ch.dreamweb.client.request.StatisticRequest_Roo_Gwt;
import ch.dreamweb.client.scaffold.ScaffoldApp;
import ch.dreamweb.client.scaffold.place.CreateAndEditProxy;
import ch.dreamweb.client.scaffold.place.FindAndEditProxy;
import ch.dreamweb.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class StatisticActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        StatisticEditView.instance().setCreating(true);
        final StatisticRequest_Roo_Gwt request = requests.statisticRequest();
        Activity activity = new CreateAndEditProxy<StatisticProxy>(StatisticProxy.class, request, ScaffoldApp.isMobile() ? StatisticMobileEditView.instance() : StatisticEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(StatisticProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new StatisticEditActivityWrapper(requests, ScaffoldApp.isMobile() ? StatisticMobileEditView.instance() : StatisticEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<ch.dreamweb.client.proxy.StatisticProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<StatisticProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        StatisticEditView.instance().setCreating(false);
        EntityProxyId<StatisticProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<StatisticProxy>(proxyId, requests, ScaffoldApp.isMobile() ? StatisticMobileEditView.instance() : StatisticEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(StatisticProxy proxy) {
                StatisticRequest_Roo_Gwt request = requests.statisticRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new StatisticEditActivityWrapper(requests, ScaffoldApp.isMobile() ? StatisticMobileEditView.instance() : StatisticEditView.instance(), activity, proxyId);
    }
}
