// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.activity;

import ch.dreamweb.client.managed.request.ApplicationRequestFactory;
import ch.dreamweb.client.managed.ui.TestStatisticDetailsView;
import ch.dreamweb.client.managed.ui.TestStatisticEditView;
import ch.dreamweb.client.managed.ui.TestStatisticListView;
import ch.dreamweb.client.managed.ui.TestStatisticMobileDetailsView;
import ch.dreamweb.client.managed.ui.TestStatisticMobileEditView;
import ch.dreamweb.client.proxy.TestStatisticProxy;
import ch.dreamweb.client.request.TestStatisticRequest_Roo_Gwt;
import ch.dreamweb.client.scaffold.ScaffoldApp;
import ch.dreamweb.client.scaffold.place.CreateAndEditProxy;
import ch.dreamweb.client.scaffold.place.FindAndEditProxy;
import ch.dreamweb.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class TestStatisticActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        TestStatisticEditView.instance().setCreating(true);
        final TestStatisticRequest_Roo_Gwt request = requests.testStatisticRequest();
        Activity activity = new CreateAndEditProxy<TestStatisticProxy>(TestStatisticProxy.class, request, ScaffoldApp.isMobile() ? TestStatisticMobileEditView.instance() : TestStatisticEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(TestStatisticProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new TestStatisticEditActivityWrapper(requests, ScaffoldApp.isMobile() ? TestStatisticMobileEditView.instance() : TestStatisticEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<ch.dreamweb.client.proxy.TestStatisticProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<TestStatisticProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        TestStatisticEditView.instance().setCreating(false);
        EntityProxyId<TestStatisticProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<TestStatisticProxy>(proxyId, requests, ScaffoldApp.isMobile() ? TestStatisticMobileEditView.instance() : TestStatisticEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(TestStatisticProxy proxy) {
                TestStatisticRequest_Roo_Gwt request = requests.testStatisticRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new TestStatisticEditActivityWrapper(requests, ScaffoldApp.isMobile() ? TestStatisticMobileEditView.instance() : TestStatisticEditView.instance(), activity, proxyId);
    }
}
