// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.dreamweb.domain;

import ch.dreamweb.domain.Setting;
import java.io.Serializable;

privileged aspect Setting_Roo_Serializable {
    
    declare parents: Setting implements Serializable;
    
    private static final long Setting.serialVersionUID = 1L;
    
}
