// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.dreamweb.domain;

import ch.dreamweb.domain.Setting;

privileged aspect Setting_Roo_JavaBean {
    
    public String Setting.getLogin() {
        return this.login;
    }
    
    public void Setting.setLogin(String login) {
        this.login = login;
    }
    
}
