// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.dreamweb.domain;

import ch.dreamweb.domain.Statistic;
import java.io.Serializable;

privileged aspect Statistic_Roo_Serializable {
    
    declare parents: Statistic implements Serializable;
    
    private static final long Statistic.serialVersionUID = 1L;
    
}
