// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.ui;

import ch.dreamweb.client.proxy.SettingProxy;
import ch.dreamweb.client.scaffold.ScaffoldMobileApp;
import ch.dreamweb.client.scaffold.ui.MobileProxyListView;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.AbstractSafeHtmlRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.text.shared.SafeHtmlRenderer;
import java.util.HashSet;
import java.util.Set;

public abstract class SettingMobileListView_Roo_Gwt extends MobileProxyListView<SettingProxy> {

    protected Set<String> paths = new HashSet<String>();

    public SettingMobileListView_Roo_Gwt(String buttonText, SafeHtmlRenderer<ch.dreamweb.client.proxy.SettingProxy> renderer) {
        super(buttonText, renderer);
    }

    public void init() {
        paths.add("login");
        paths.add("id");
    }
}
