// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.ui;

import ch.dreamweb.client.proxy.StatisticProxy;
import ch.dreamweb.client.scaffold.place.ProxyDetailsView;
import ch.dreamweb.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class StatisticDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<StatisticProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement login;

    @UiField
    SpanElement datetime;

    @UiField
    SpanElement trainingday;

    @UiField
    SpanElement unit;

    @UiField
    SpanElement rightexercices;

    @UiField
    SpanElement wrongexercices;

    @UiField
    SpanElement levelsum;

    @UiField
    SpanElement levelsumright;

    @UiField
    SpanElement averagelevelright;

    @UiField
    SpanElement highestlevelindex;

    @UiField
    SpanElement stepsperlevel;

    @UiField
    SpanElement history;

    @UiField
    SpanElement version;

    StatisticProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(StatisticProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        login.setInnerText(proxy.getLogin() == null ? "" : String.valueOf(proxy.getLogin()));
        datetime.setInnerText(proxy.getDatetime() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getDatetime()));
        trainingday.setInnerText(proxy.getTrainingday() == null ? "" : String.valueOf(proxy.getTrainingday()));
        unit.setInnerText(proxy.getUnit() == null ? "" : String.valueOf(proxy.getUnit()));
        rightexercices.setInnerText(proxy.getRightexercices() == null ? "" : String.valueOf(proxy.getRightexercices()));
        wrongexercices.setInnerText(proxy.getWrongexercices() == null ? "" : String.valueOf(proxy.getWrongexercices()));
        levelsum.setInnerText(proxy.getLevelsum() == null ? "" : String.valueOf(proxy.getLevelsum()));
        levelsumright.setInnerText(proxy.getLevelsumright() == null ? "" : String.valueOf(proxy.getLevelsumright()));
        averagelevelright.setInnerText(proxy.getAveragelevelright() == null ? "" : String.valueOf(proxy.getAveragelevelright()));
        highestlevelindex.setInnerText(proxy.getHighestlevelindex() == null ? "" : String.valueOf(proxy.getHighestlevelindex()));
        stepsperlevel.setInnerText(proxy.getStepsperlevel() == null ? "" : String.valueOf(proxy.getStepsperlevel()));
        history.setInnerText(proxy.getHistory() == null ? "" : String.valueOf(proxy.getHistory()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(StatisticProxyRenderer.instance().render(proxy));
    }
}
