// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.dreamweb.client.managed.ui;

import ch.dreamweb.client.proxy.TestStatisticProxy;
import ch.dreamweb.client.scaffold.place.ProxyDetailsView;
import ch.dreamweb.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class TestStatisticDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<TestStatisticProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement login;

    @UiField
    SpanElement datetime;

    @UiField
    SpanElement test;

    @UiField
    SpanElement testround;

    @UiField
    SpanElement spanscore;

    @UiField
    SpanElement trialscore;

    @UiField
    SpanElement trialscore_version;

    @UiField
    SpanElement history;

    @UiField
    SpanElement version;

    TestStatisticProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(TestStatisticProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        login.setInnerText(proxy.getLogin() == null ? "" : String.valueOf(proxy.getLogin()));
        datetime.setInnerText(proxy.getDatetime() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getDatetime()));
        test.setInnerText(proxy.getTest() == null ? "" : String.valueOf(proxy.getTest()));
        testround.setInnerText(proxy.getTestround() == null ? "" : String.valueOf(proxy.getTestround()));
        spanscore.setInnerText(proxy.getSpanscore() == null ? "" : String.valueOf(proxy.getSpanscore()));
        trialscore.setInnerText(proxy.getTrialscore() == null ? "" : String.valueOf(proxy.getTrialscore()));
        trialscore_version.setInnerText(proxy.getTrialscore_version() == null ? "" : String.valueOf(proxy.getTrialscore_version()));
        history.setInnerText(proxy.getHistory() == null ? "" : String.valueOf(proxy.getHistory()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(TestStatisticProxyRenderer.instance().render(proxy));
    }
}
